
import os
import numpy as np
import pandas as pd
import torch
from torch import nn
import sys

from src.data.datamodule import DataLoaders
from src.data.pred_dataset import *

DSETS = ['ettm1', 'ettm2', 'etth1', 'etth2', 'electricity',
         'traffic', 'illness', 'weather', 'exchange'
        ]

# 数据集根目录：相对于此文件的位置
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_DATASETS_ROOT = os.path.join(_SCRIPT_DIR, 'datasets')


class ChannelSliceDataset(torch.utils.data.Dataset):
    """Dataset wrapper that keeps a channel range or arbitrary channel indices."""

    def __init__(self, dataset, channel_start=None, channel_end=None, channel_indices=None):
        self.dataset = dataset
        self.full_vars = dataset[0][0].shape[1]
        self.channel_indices = None

        if channel_indices is not None:
            if isinstance(channel_indices, str):
                channel_indices = [int(x) for x in channel_indices.split(',') if x.strip()]
            channel_indices = [int(x) for x in channel_indices]
            if not channel_indices:
                raise ValueError("channel_indices is empty")
            if min(channel_indices) < 0 or max(channel_indices) >= self.full_vars:
                raise ValueError(
                    f"Invalid channel_indices {channel_indices} for dataset with {self.full_vars} channels"
                )
            # Backward-compatibility: a channel group containing every channel
            # should be a no-op even if its order was generated by frequency
            # grouping. Older datautils ignored channel_indices entirely; without
            # this guard, single-group datasets like ETTh/ETTm would silently
            # reorder channels and diverge from the old results.
            if len(channel_indices) == self.full_vars and sorted(channel_indices) == list(range(self.full_vars)):
                self.channel_start = 0
                self.channel_end = self.full_vars
            else:
                self.channel_indices = torch.tensor(channel_indices, dtype=torch.long)
                self.channel_start = min(channel_indices)
                self.channel_end = max(channel_indices) + 1
        else:
            start = 0 if channel_start is None else int(channel_start)
            end = self.full_vars if channel_end is None else int(channel_end)
            if not (0 <= start < end <= self.full_vars):
                raise ValueError(
                    f"Invalid channel range [{start}, {end}) for dataset with {self.full_vars} channels"
                )
            self.channel_start = start
            self.channel_end = end

    def __len__(self):
        return len(self.dataset)

    def __getattr__(self, name):
        return getattr(self.dataset, name)

    def __getitem__(self, idx):
        item = self.dataset[idx]
        values = list(item)
        # Time-series tensors are returned as [T, C]. Time feature tensors, if
        # present, are kept unchanged because they are timestamp features.
        if self.channel_indices is not None:
            idx = self.channel_indices
            values[0] = values[0].index_select(1, idx) if torch.is_tensor(values[0]) else values[0][:, idx.numpy()]
            values[1] = values[1].index_select(1, idx) if torch.is_tensor(values[1]) else values[1][:, idx.numpy()]
        else:
            values[0] = values[0][:, self.channel_start:self.channel_end]
            values[1] = values[1][:, self.channel_start:self.channel_end]
        return tuple(values)


def get_dls(params):
    
    assert params.dset in DSETS, f"Unrecognized dset (`{params.dset}`). Options include: {DSETS}"
    if not hasattr(params,'use_time_features'): params.use_time_features = False

    # 使用绝对路径，确保从任何目录运行都能找到数据集
    root_path = _DATASETS_ROOT + '/'

    # 通用参数
    # 如果没有 target_points，使用默认值（基于 context_points 或 progressive_step_size）
    if not hasattr(params, 'target_points') or params.target_points is None:
        # 如果有 progressive_step_size，使用它来计算 target_points
        if hasattr(params, 'progressive_step_size') and params.progressive_step_size is not None:
            # 假设 patch_size 存在，如果没有则使用默认值
            patch_size = getattr(params, 'patch_size', 16)
            params.target_points = params.progressive_step_size * patch_size
        else:
            # 默认使用 context_points 的一部分
            params.target_points = params.context_points // 4
    
    size = [params.context_points, 0, params.target_points]
    
    # 数据集配置映射
    dataset_config = {
        'ettm1': (Dataset_ETT_minute, 'ETTm1.csv'),
        'ettm2': (Dataset_ETT_minute, 'ETTm2.csv'),
        'etth1': (Dataset_ETT_hour, 'ETTh1.csv'),
        'etth2': (Dataset_ETT_hour, 'ETTh2.csv'),
        'electricity': (Dataset_Custom, 'electricity.csv'),
        'traffic': (Dataset_Custom, 'traffic.csv'),
        'weather': (Dataset_Custom, 'weather.csv'),
        'illness': (Dataset_Custom, 'national_illness.csv'),
        'exchange': (Dataset_Custom, 'exchange_rate.csv'),
    }
    
    datasetCls, data_path = dataset_config[params.dset]

    channel_start = getattr(params, 'channel_start', None)
    channel_end = getattr(params, 'channel_end', None)
    channel_indices = getattr(params, 'channel_indices', None)

    # argparse may pass -1/None-like values when users want the full channel set.
    if channel_start is not None and int(channel_start) < 0:
        channel_start = None
    if channel_end is not None and int(channel_end) < 0:
        channel_end = None
    if channel_start is not None:
        channel_start = int(channel_start)
    if channel_end is not None:
        channel_end = int(channel_end)

    use_channel_slice = channel_indices is not None or channel_start is not None or channel_end is not None
    baseDatasetCls = datasetCls
    if use_channel_slice:
        def datasetCls(**kwargs):
            return ChannelSliceDataset(baseDatasetCls(**kwargs), channel_start, channel_end, channel_indices)

    dls = DataLoaders(
        datasetCls=datasetCls,
        dataset_kwargs={
            'root_path': root_path,
            'data_path': data_path,
            'features': params.features,
            'scale': True,
            'size': size,
            'use_time_features': params.use_time_features
        },
        batch_size=params.batch_size,
        workers=params.num_workers,
    )
    if use_channel_slice:
        dls.channel_start = dls.train.dataset.channel_start
        dls.channel_end = dls.train.dataset.channel_end
        dls.channel_indices = (
            dls.train.dataset.channel_indices.tolist()
            if dls.train.dataset.channel_indices is not None else None
        )
        dls.full_vars = dls.train.dataset.full_vars
    else:
        dls.channel_start = None
        dls.channel_end = None
        dls.channel_indices = None
        dls.full_vars = dls.train.dataset[0][0].shape[1]

    # dataset is assume to have dimension len x nvars
    dls.vars, dls.len = dls.train.dataset[0][0].shape[1], params.context_points
    dls.c = dls.train.dataset[0][1].shape[0]
    return dls



if __name__ == "__main__":
    class Params:
        dset= 'etth2'
        context_points= 384
        target_points= 96
        batch_size= 64
        num_workers= 8
        with_ray= False
        features='M'
    params = Params 
    dls = get_dls(params)
    for i, batch in enumerate(dls.valid):
        print(i, len(batch), batch[0].shape, batch[1].shape)
    breakpoint()
